[profile.release]
strip = "debuginfo"

[workspace]
resolver = "2"
members = [
    "cln-rpc",
    "cln-grpc",
    "plugins",
    "plugins/grpc-plugin",
    "plugins/rest-plugin",
    "plugins/lsps-plugin",
    "plugins/wss-proxy-plugin",
]
