[tool.poetry]
name = "pyln-bolt7"
version = "1.0.2.186.post0"
description = "BOLT7"
authors = ["Rusty Russell"]
license = "BSD-MIT"

packages = [
  { include = "pyln/spec/bolt7" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pyln-proto = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
