[tool.poetry]
name = "pyln-client"
version = "0.10.2"
description = "Client library and plugin library for c-lightning"
authors = ["Christian Decker <decker.christian@gmail.com>"]
license = "BSD-MIT"

packages = [
  { include = "pyln/client" },
]

[tool.poetry.dependencies]
python = "^3.7"
pyln-proto = { path = "../pyln-proto" }
pyln-bolt7 = { path = "../pyln-spec/bolt7" }

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
