[tool.poetry]
name = "pyln-bolt2"
version = "1.0.2.187.post0"
description = "A pure python implementation of BOLT2"
authors = ["Rusty Russell <rusty@blockstream.com>"]
license = "MIT"

packages = [
  { include = "pyln/spec/bolt2" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pyln-proto = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
