name: ReadMe Sync

on:
  push:
    branches:
      - 'master'
    paths:
      - 'doc/**'
  workflow_dispatch:

jobs:
  rdme-docs-sync:  
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo ðŸ“š
        uses: actions/checkout@v4

      - name: Sync doc/getting-started/ ðŸš€
        uses: readmeio/rdme@v8
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs doc/getting-started --key=${{ env.README_API_KEY }} --version=1
            
      - name: Sync doc/beginners-guide/ ðŸš€
        uses: readmeio/rdme@v8
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs doc/beginners-guide --key=${{ env.README_API_KEY }} --version=1
      
      - name: Sync doc/node-operators-guide/ ðŸš€
        uses: readmeio/rdme@v8
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs doc/node-operators-guide --key=${{ env.README_API_KEY }} --version=1
      
      - name: Sync doc/developers-guide/ ðŸš€
        uses: readmeio/rdme@v8
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs doc/developers-guide --key=${{ env.README_API_KEY }} --version=1
      
      - name: Sync doc/contributing-to-core-lightning/ ðŸš€
        uses: readmeio/rdme@v8
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs doc/contribute-to-core-lightning --key=${{ env.README_API_KEY }} --version=1
