name: ReadMe RPC Sync

on:
  push:
    branches:
      - 'master'
    paths:
      - 'doc/schemas/lightning-*.json'
      - 'doc/*.1.md'
      - 'doc/*.5.md'
      - 'doc/*.8.md'
      - 'doc/lightningd-*.7.md'
  workflow_dispatch:

jobs:
  rdme-rpc-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install python modules
      run: |
        python -m pip install requests mako

    - name: Install dependencies
      run: bash -x .github/scripts/setup.sh

    - name: Build (including rpc .md files)
      run: |
        ./configure --enable-debugbuild
        make -j $(nproc)

    - name: Set environment variable and run
      env:
        README_API_KEY: ${{ secrets.README_API_KEY }}  
      run: python .github/scripts/sync-rpc-cmds.py
